"""Emits gen/stubs.c and gen/proxy.def from a system DLL's export directory.

Usage: python gen_proxy.py [source_dll] [output_dir]
"""

import os
import struct
import sys

DEFAULT_SOURCE = r"C:\Windows\SysWOW64\dbghelp.dll"


def rva_to_offset(sections, rva):
    for va, vsize, raw_ptr, raw_size in sections:
        if va <= rva < va + max(vsize, raw_size):
            return raw_ptr + (rva - va)
    return rva


def read_cstring(data, offset):
    return data[offset:data.index(b"\0", offset)].decode("ascii")


def parse_exports(path):
    with open(path, "rb") as f:
        data = f.read()

    pe = struct.unpack_from("<I", data, 0x3C)[0]
    if data[pe:pe + 4] != b"PE\0\0":
        sys.exit("not a PE image: " + path)

    coff = pe + 4
    section_count = struct.unpack_from("<H", data, coff + 2)[0]
    opt_size = struct.unpack_from("<H", data, coff + 16)[0]
    opt = coff + 20

    magic = struct.unpack_from("<H", data, opt)[0]
    if magic != 0x10B:
        sys.exit("expected a 32-bit PE32 image, got optional header magic 0x%X" % magic)

    export_rva, export_size = struct.unpack_from("<II", data, opt + 96)

    sections = []
    for i in range(section_count):
        header = opt + opt_size + i * 40
        vsize, va, raw_size, raw_ptr = struct.unpack_from("<IIII", data, header + 8)
        sections.append((va, vsize, raw_ptr, raw_size))

    if export_rva == 0:
        sys.exit("no export directory in " + path)

    d = rva_to_offset(sections, export_rva)
    base, func_count, name_count = struct.unpack_from("<III", data, d + 16)
    funcs_rva, names_rva, ordinals_rva = struct.unpack_from("<III", data, d + 28)

    funcs = rva_to_offset(sections, funcs_rva)
    names = rva_to_offset(sections, names_rva)
    ordinals = rva_to_offset(sections, ordinals_rva)

    # AddressOfNameOrdinals holds indices into AddressOfFunctions, not ordinals.
    name_by_index = {}
    for i in range(name_count):
        index = struct.unpack_from("<H", data, ordinals + i * 2)[0]
        name_rva = struct.unpack_from("<I", data, names + i * 4)[0]
        name_by_index[index] = read_cstring(data, rva_to_offset(sections, name_rva))

    exports = []
    for i in range(func_count):
        rva = struct.unpack_from("<I", data, funcs + i * 4)[0]
        if rva == 0:
            continue
        forwarder = export_rva <= rva < export_rva + export_size
        exports.append((name_by_index.get(i), base + i, forwarder))

    return exports, base


def write_stubs(path, source_dll, exports):
    lines = []
    lines.append("/* Generated by tools/gen_proxy.py from %s. Do not edit. */" % source_dll)
    lines.append("#include <windows.h>")
    lines.append("")
    lines.append("#define PROXY_EXPORT_COUNT %d" % len(exports))
    lines.append("")
    lines.append('const wchar_t g_realDllPath[] = L"%s";' % source_dll.replace("\\", "\\\\"))
    lines.append("")
    lines.append("const char *const g_names[PROXY_EXPORT_COUNT] = {")
    for name, _, _ in exports:
        lines.append('    %s,' % ('"%s"' % name if name else "NULL"))
    lines.append("};")
    lines.append("")
    lines.append("const WORD g_ordinals[PROXY_EXPORT_COUNT] = {")
    for _, ordinal, _ in exports:
        lines.append("    %d," % ordinal)
    lines.append("};")
    lines.append("")
    lines.append("void *g_real[PROXY_EXPORT_COUNT];")
    lines.append("")
    lines.append("void ProxyThunk(void);")
    lines.append("")
    for i in range(len(exports)):
        lines.append("__declspec(naked) void Stub_%d(void) { __asm mov eax, %d __asm jmp ProxyThunk }"
                     % (i, i))
    lines.append("")

    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines))


def write_def(path, exports):
    lines = ["EXPORTS"]
    for i, (name, ordinal, _) in enumerate(exports):
        if name:
            lines.append("    %s = Stub_%d @%d" % (name, i, ordinal))
        else:
            lines.append("    Stub_%d @%d NONAME" % (i, ordinal))
    lines.append("")

    with open(path, "w", newline="\r\n") as f:
        f.write("\n".join(lines))


def main():
    source_dll = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SOURCE)
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = os.path.abspath(sys.argv[2] if len(sys.argv) > 2 else os.path.join(root, "gen"))

    exports, base = parse_exports(source_dll)
    os.makedirs(out_dir, exist_ok=True)
    write_stubs(os.path.join(out_dir, "stubs.c"), source_dll, exports)
    write_def(os.path.join(out_dir, "proxy.def"), exports)

    named = sum(1 for name, _, _ in exports if name)
    forwarders = sum(1 for _, _, forwarder in exports if forwarder)
    print("source      : %s" % source_dll)
    print("output      : %s" % out_dir)
    print("exports     : %d (%d named, %d ordinal-only)" % (len(exports), named, len(exports) - named))
    print("ordinals    : %d..%d (base %d)" % (exports[0][1], exports[-1][1], base))
    print("forwarders  : %d" % forwarders)


if __name__ == "__main__":
    main()
